import { BankConfiguration } from "AppTypes";

export const banks: BankConfiguration[] = [
  {
    name: "Absa Bank Limited",
    universalBankCode: "632005",
    swiftCode: "ABSAZAJJXXX",
    accountIndicator: 4,
    weightingDigits: null,
    fudgeFactor: null,
    modulus: null,
    exceptCode: "f",
    validLengths: "8,9,10,11",
  },
  {
    name: "African Bank Limited",
    universalBankCode: "430000",
    swiftCode: "AFRCZAJJXXX",
    accountIndicator: null,
    weightingDigits: null,
    fudgeFactor: null,
    modulus: null,
    exceptCode: null,
    validLengths: null,
  },
  {
    name: "Bidvest Bank Limited",
    universalBankCode: "462005",
    swiftCode: "BIDBZAJJXXX",
    accountIndicator: null,
    weightingDigits: null,
    fudgeFactor: null,
    modulus: null,
    exceptCode: null,
    validLengths: null,
  },
  {
    name: "Capitec Bank Limited",
    universalBankCode: "470010",
    swiftCode: "CABLZAJJXXX",
    accountIndicator: 4,
    weightingDigits: "21987654321",
    fudgeFactor: 0,
    modulus: 11,
    exceptCode: null,
    validLengths: "10",
  },
  {
    name: "Discovery Bank Limited",
    universalBankCode: "679000",
    swiftCode: "DISCZAJJ",
    accountIndicator: null,
    weightingDigits: null,
    fudgeFactor: null,
    modulus: null,
    exceptCode: null,
    validLengths: null,
  },
  {
    name: "First National Bank (FNB)",
    universalBankCode: "250655",
    swiftCode: "FIRNZAJJ",
    accountIndicator: 4,
    weightingDigits: "12121212121",
    fudgeFactor: 0,
    modulus: 10,
    exceptCode: null,
    validLengths: "11",
  },
  {
    name: "FirstRand Bank - A subsidiary of First Rand Limited",
    universalBankCode: "250655",
    swiftCode: "FIRNZAJJRSL",
    accountIndicator: null,
    weightingDigits: null,
    fudgeFactor: null,
    modulus: null,
    exceptCode: null,
    validLengths: null,
  },
  {
    name: "Grindrod Bank Limited",
    universalBankCode: "223626",
    swiftCode: "GRIDZAJJXXX",
    accountIndicator: null,
    weightingDigits: null,
    fudgeFactor: null,
    modulus: null,
    exceptCode: null,
    validLengths: null,
  },
  {
    name: "Investec Bank Limited",
    universalBankCode: "580105",
    swiftCode: "IVESZAJJXXX",
    accountIndicator: 4,
    weightingDigits: "000NJHD7531",
    fudgeFactor: 0,
    modulus: 11,
    exceptCode: null,
    validLengths: "11",
  },
  {
    name: "Mercantile Bank Limited",
    universalBankCode: "450105",
    swiftCode: "LISAZAJJXXX",
    accountIndicator: 4,
    weightingDigits: "1A987654321",
    fudgeFactor: 0,
    modulus: 11,
    exceptCode: null,
    validLengths: "10",
  },
  {
    name: "Nedbank Limited",
    universalBankCode: "198765",
    swiftCode: "NEDSZAJJXXX",
    accountIndicator: 4,
    weightingDigits: "11987654321",
    fudgeFactor: 9,
    modulus: 11,
    exceptCode: null,
    validLengths: "10,11",
  },
  {
    name: "Old Mutual",
    universalBankCode: "462005",
    swiftCode: "OMAMZAJC XXX",
    accountIndicator: null,
    weightingDigits: null,
    fudgeFactor: null,
    modulus: null,
    exceptCode: null,
    validLengths: null,
  },
  {
    name: "Sasfin Bank Limited",
    universalBankCode: "683000",
    swiftCode: "SASFZAJJXXX",
    accountIndicator: null,
    weightingDigits: null,
    fudgeFactor: null,
    modulus: null,
    exceptCode: null,
    validLengths: null,
  },
  {
    name: "Standard Bank of South Africa",
    universalBankCode: "051001",
    swiftCode: "SBZAZAJJ",
    accountIndicator: 4,
    weightingDigits: "11987654321",
    fudgeFactor: 0,
    modulus: 11,
    exceptCode: "m",
    validLengths: "9,11",
  },
  {
    name: "SA Post Bank (Post Office)",
    universalBankCode: "460005",
    swiftCode: "SBZAZAJJ",
    accountIndicator: null,
    weightingDigits: null,
    fudgeFactor: null,
    modulus: null,
    exceptCode: null,
    validLengths: null,
  },
  {
    name: "Tyme Bank",
    universalBankCode: "678910",
    swiftCode: "CBZAZAJJ",
    accountIndicator: null,
    weightingDigits: null,
    fudgeFactor: null,
    modulus: null,
    exceptCode: null,
    validLengths: null,
  },
];
